version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: weather_app
    ports:
      - "5432:5432"

  web:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db
